### ISSUE TITLE
More context in the README file

### ISSUE THREAD

**Issue by PeterMortensen** [markgbeckett/jupiter_ace#2]
I suggest adding more context to the README file (file *README.md*).

At a minimum, link to Wikipedia. And if it can run on some (particular) emulator or if real hardware is required.

[The tweet][1] says ZX Spectrum with Abersoft Forth, whereas the name of this repository (and the current content of the README file) suggests Jupiter Ace. The README file could contain information that would (indirectly) answer that question. Also, if Abersoft Forth is freely available (or not) and if it would be feasible for others to reproduce this (result) - and if yes, some instructions on how to reproduce it.

 [1]: https://twitter.com/markgbeckett/status/1328023185468641281

**Comment by markgbeckett** [comment]
Hi Peter, Thanks. It's on my to-do list to expand on this. I'm conscious that, unless you are familar with Abersoft Forth, the instructions will not be very useful. I also plan to add a tape image for those who wish to try the program in an emulator.

**Comment by markgbeckett** [comment]
README updated and tape images added for easier access.
